#!/usr/bin/env python3
"""
Generate test data for OpenCL vector load/store functions
Tests vload2, vload3, vload4 and vstore2, vstore3, vstore4
"""

import json


def create_vload_vstore_test_data():
    """Create test data for vload and vstore functions"""

    functions = []

    # vload2 - load float2 from scalar array
    functions.append(
        {
            "name": "vload2_float",
            "kernel_name": "test_vload2_float",
            "input_type": "float",  # scalar array input
            "output_type": "float2",  # vector output
            "num_inputs": 2,  # scalar array + offset
            "tests": [
                # offset=0: load from [0,1]
                {"inputs": [[1.0, 2.0, 3.0, 4.0], 0], "expected": [1.0, 2.0]},
                # offset=1: load from [2,3]
                {"inputs": [[1.0, 2.0, 3.0, 4.0], 1], "expected": [3.0, 4.0]},
                # offset=0: different values
                {"inputs": [[10.0, 20.0, 30.0, 40.0], 0], "expected": [10.0, 20.0]},
                # offset=1
                {"inputs": [[10.0, 20.0, 30.0, 40.0], 1], "expected": [30.0, 40.0]},
                # offset=0: negative values
                {"inputs": [[-1.0, -2.0, -3.0, -4.0], 0], "expected": [-1.0, -2.0]},
                # offset=1
                {"inputs": [[-1.0, -2.0, -3.0, -4.0], 1], "expected": [-3.0, -4.0]},
                # offset=0: mixed values
                {"inputs": [[0.5, 1.5, 2.5, 3.5], 0], "expected": [0.5, 1.5]},
                # offset=1
                {"inputs": [[0.5, 1.5, 2.5, 3.5], 1], "expected": [2.5, 3.5]},
                # offset=0: zeros
                {"inputs": [[0.0, 0.0, 1.0, 1.0], 0], "expected": [0.0, 0.0]},
                # offset=1
                {"inputs": [[0.0, 0.0, 1.0, 1.0], 1], "expected": [1.0, 1.0]},
            ],
        }
    )

    # vload3 - load float3 from scalar array
    functions.append(
        {
            "name": "vload3_float",
            "kernel_name": "test_vload3_float",
            "input_type": "float",
            "output_type": "float3",
            "num_inputs": 2,  # scalar array + offset
            "tests": [
                # offset=0: load from [0,1,2]
                {"inputs": [[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], 0], "expected": [1.0, 2.0, 3.0]},
                # offset=1: load from [3,4,5]
                {"inputs": [[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], 1], "expected": [4.0, 5.0, 6.0]},
                # offset=0: different values
                {
                    "inputs": [[10.0, 20.0, 30.0, 40.0, 50.0, 60.0], 0],
                    "expected": [10.0, 20.0, 30.0],
                },
                # offset=1
                {
                    "inputs": [[10.0, 20.0, 30.0, 40.0, 50.0, 60.0], 1],
                    "expected": [40.0, 50.0, 60.0],
                },
                # offset=0: negative values
                {
                    "inputs": [[-1.0, -2.0, -3.0, -4.0, -5.0, -6.0], 0],
                    "expected": [-1.0, -2.0, -3.0],
                },
                # offset=1
                {
                    "inputs": [[-1.0, -2.0, -3.0, -4.0, -5.0, -6.0], 1],
                    "expected": [-4.0, -5.0, -6.0],
                },
                # offset=0: fractional
                {"inputs": [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6], 0], "expected": [0.1, 0.2, 0.3]},
                # offset=1
                {"inputs": [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6], 1], "expected": [0.4, 0.5, 0.6]},
                # offset=0: zeros and ones
                {"inputs": [[0.0, 0.0, 0.0, 1.0, 1.0, 1.0], 0], "expected": [0.0, 0.0, 0.0]},
                # offset=1
                {"inputs": [[0.0, 0.0, 0.0, 1.0, 1.0, 1.0], 1], "expected": [1.0, 1.0, 1.0]},
            ],
        }
    )

    # vload4 - load float4 from scalar array
    functions.append(
        {
            "name": "vload4_float",
            "kernel_name": "test_vload4_float",
            "input_type": "float",
            "output_type": "float4",
            "num_inputs": 2,  # scalar array + offset
            "tests": [
                # offset=0: load from [0,1,2,3]
                {
                    "inputs": [[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0], 0],
                    "expected": [1.0, 2.0, 3.0, 4.0],
                },
                # offset=1: load from [4,5,6,7]
                {
                    "inputs": [[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0], 1],
                    "expected": [5.0, 6.0, 7.0, 8.0],
                },
                # offset=0: different values
                {
                    "inputs": [[10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0], 0],
                    "expected": [10.0, 20.0, 30.0, 40.0],
                },
                # offset=1
                {
                    "inputs": [[10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0], 1],
                    "expected": [50.0, 60.0, 70.0, 80.0],
                },
                # offset=0: negative values
                {
                    "inputs": [[-1.0, -2.0, -3.0, -4.0, -5.0, -6.0, -7.0, -8.0], 0],
                    "expected": [-1.0, -2.0, -3.0, -4.0],
                },
                # offset=1
                {
                    "inputs": [[-1.0, -2.0, -3.0, -4.0, -5.0, -6.0, -7.0, -8.0], 1],
                    "expected": [-5.0, -6.0, -7.0, -8.0],
                },
                # offset=0: fractional values
                {
                    "inputs": [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8], 0],
                    "expected": [0.1, 0.2, 0.3, 0.4],
                },
                # offset=1
                {
                    "inputs": [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8], 1],
                    "expected": [0.5, 0.6, 0.7, 0.8],
                },
                # offset=0: zeros and ones
                {
                    "inputs": [[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0], 0],
                    "expected": [0.0, 0.0, 0.0, 0.0],
                },
                # offset=1
                {
                    "inputs": [[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0], 1],
                    "expected": [1.0, 1.0, 1.0, 1.0],
                },
            ],
        }
    )

    # vload8 - load float8 from scalar array
    functions.append(
        {
            "name": "vload8_float",
            "kernel_name": "test_vload8_float",
            "input_type": "float",
            "output_type": "float8",
            "num_inputs": 2,  # scalar array + offset
            "tests": [
                # offset=0: load from [0-7]
                {
                    "inputs": [
                        [
                            1.0,
                            2.0,
                            3.0,
                            4.0,
                            5.0,
                            6.0,
                            7.0,
                            8.0,
                            9.0,
                            10.0,
                            11.0,
                            12.0,
                            13.0,
                            14.0,
                            15.0,
                            16.0,
                        ],
                        0,
                    ],
                    "expected": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0],
                },
                # offset=1: load from [8-15]
                {
                    "inputs": [
                        [
                            1.0,
                            2.0,
                            3.0,
                            4.0,
                            5.0,
                            6.0,
                            7.0,
                            8.0,
                            9.0,
                            10.0,
                            11.0,
                            12.0,
                            13.0,
                            14.0,
                            15.0,
                            16.0,
                        ],
                        1,
                    ],
                    "expected": [9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0],
                },
                # offset=0: different values
                {
                    "inputs": [
                        [
                            10.0,
                            20.0,
                            30.0,
                            40.0,
                            50.0,
                            60.0,
                            70.0,
                            80.0,
                            90.0,
                            100.0,
                            110.0,
                            120.0,
                            130.0,
                            140.0,
                            150.0,
                            160.0,
                        ],
                        0,
                    ],
                    "expected": [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            10.0,
                            20.0,
                            30.0,
                            40.0,
                            50.0,
                            60.0,
                            70.0,
                            80.0,
                            90.0,
                            100.0,
                            110.0,
                            120.0,
                            130.0,
                            140.0,
                            150.0,
                            160.0,
                        ],
                        1,
                    ],
                    "expected": [90.0, 100.0, 110.0, 120.0, 130.0, 140.0, 150.0, 160.0],
                },
                # offset=0: negative values
                {
                    "inputs": [
                        [
                            -1.0,
                            -2.0,
                            -3.0,
                            -4.0,
                            -5.0,
                            -6.0,
                            -7.0,
                            -8.0,
                            -9.0,
                            -10.0,
                            -11.0,
                            -12.0,
                            -13.0,
                            -14.0,
                            -15.0,
                            -16.0,
                        ],
                        0,
                    ],
                    "expected": [-1.0, -2.0, -3.0, -4.0, -5.0, -6.0, -7.0, -8.0],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            -1.0,
                            -2.0,
                            -3.0,
                            -4.0,
                            -5.0,
                            -6.0,
                            -7.0,
                            -8.0,
                            -9.0,
                            -10.0,
                            -11.0,
                            -12.0,
                            -13.0,
                            -14.0,
                            -15.0,
                            -16.0,
                        ],
                        1,
                    ],
                    "expected": [-9.0, -10.0, -11.0, -12.0, -13.0, -14.0, -15.0, -16.0],
                },
                # offset=0: fractional
                {
                    "inputs": [
                        [
                            0.1,
                            0.2,
                            0.3,
                            0.4,
                            0.5,
                            0.6,
                            0.7,
                            0.8,
                            0.9,
                            1.0,
                            1.1,
                            1.2,
                            1.3,
                            1.4,
                            1.5,
                            1.6,
                        ],
                        0,
                    ],
                    "expected": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            0.1,
                            0.2,
                            0.3,
                            0.4,
                            0.5,
                            0.6,
                            0.7,
                            0.8,
                            0.9,
                            1.0,
                            1.1,
                            1.2,
                            1.3,
                            1.4,
                            1.5,
                            1.6,
                        ],
                        1,
                    ],
                    "expected": [0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6],
                },
                # offset=0: zeros and ones
                {
                    "inputs": [
                        [
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                        ],
                        0,
                    ],
                    "expected": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                        ],
                        1,
                    ],
                    "expected": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                },
            ],
        }
    )

    # vload16 - load float16 from scalar array
    functions.append(
        {
            "name": "vload16_float",
            "kernel_name": "test_vload16_float",
            "input_type": "float",
            "output_type": "float16",
            "num_inputs": 2,  # scalar array + offset
            "tests": [
                # offset=0: load from [0-15]
                {
                    "inputs": [
                        [
                            1.0,
                            2.0,
                            3.0,
                            4.0,
                            5.0,
                            6.0,
                            7.0,
                            8.0,
                            9.0,
                            10.0,
                            11.0,
                            12.0,
                            13.0,
                            14.0,
                            15.0,
                            16.0,
                            17.0,
                            18.0,
                            19.0,
                            20.0,
                            21.0,
                            22.0,
                            23.0,
                            24.0,
                            25.0,
                            26.0,
                            27.0,
                            28.0,
                            29.0,
                            30.0,
                            31.0,
                            32.0,
                        ],
                        0,
                    ],
                    "expected": [
                        1.0,
                        2.0,
                        3.0,
                        4.0,
                        5.0,
                        6.0,
                        7.0,
                        8.0,
                        9.0,
                        10.0,
                        11.0,
                        12.0,
                        13.0,
                        14.0,
                        15.0,
                        16.0,
                    ],
                },
                # offset=1: load from [16-31]
                {
                    "inputs": [
                        [
                            1.0,
                            2.0,
                            3.0,
                            4.0,
                            5.0,
                            6.0,
                            7.0,
                            8.0,
                            9.0,
                            10.0,
                            11.0,
                            12.0,
                            13.0,
                            14.0,
                            15.0,
                            16.0,
                            17.0,
                            18.0,
                            19.0,
                            20.0,
                            21.0,
                            22.0,
                            23.0,
                            24.0,
                            25.0,
                            26.0,
                            27.0,
                            28.0,
                            29.0,
                            30.0,
                            31.0,
                            32.0,
                        ],
                        1,
                    ],
                    "expected": [
                        17.0,
                        18.0,
                        19.0,
                        20.0,
                        21.0,
                        22.0,
                        23.0,
                        24.0,
                        25.0,
                        26.0,
                        27.0,
                        28.0,
                        29.0,
                        30.0,
                        31.0,
                        32.0,
                    ],
                },
                # offset=0: different values
                {
                    "inputs": [
                        [
                            10.0,
                            20.0,
                            30.0,
                            40.0,
                            50.0,
                            60.0,
                            70.0,
                            80.0,
                            90.0,
                            100.0,
                            110.0,
                            120.0,
                            130.0,
                            140.0,
                            150.0,
                            160.0,
                            170.0,
                            180.0,
                            190.0,
                            200.0,
                            210.0,
                            220.0,
                            230.0,
                            240.0,
                            250.0,
                            260.0,
                            270.0,
                            280.0,
                            290.0,
                            300.0,
                            310.0,
                            320.0,
                        ],
                        0,
                    ],
                    "expected": [
                        10.0,
                        20.0,
                        30.0,
                        40.0,
                        50.0,
                        60.0,
                        70.0,
                        80.0,
                        90.0,
                        100.0,
                        110.0,
                        120.0,
                        130.0,
                        140.0,
                        150.0,
                        160.0,
                    ],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            10.0,
                            20.0,
                            30.0,
                            40.0,
                            50.0,
                            60.0,
                            70.0,
                            80.0,
                            90.0,
                            100.0,
                            110.0,
                            120.0,
                            130.0,
                            140.0,
                            150.0,
                            160.0,
                            170.0,
                            180.0,
                            190.0,
                            200.0,
                            210.0,
                            220.0,
                            230.0,
                            240.0,
                            250.0,
                            260.0,
                            270.0,
                            280.0,
                            290.0,
                            300.0,
                            310.0,
                            320.0,
                        ],
                        1,
                    ],
                    "expected": [
                        170.0,
                        180.0,
                        190.0,
                        200.0,
                        210.0,
                        220.0,
                        230.0,
                        240.0,
                        250.0,
                        260.0,
                        270.0,
                        280.0,
                        290.0,
                        300.0,
                        310.0,
                        320.0,
                    ],
                },
                # offset=0: negative values
                {
                    "inputs": [
                        [
                            -1.0,
                            -2.0,
                            -3.0,
                            -4.0,
                            -5.0,
                            -6.0,
                            -7.0,
                            -8.0,
                            -9.0,
                            -10.0,
                            -11.0,
                            -12.0,
                            -13.0,
                            -14.0,
                            -15.0,
                            -16.0,
                            -17.0,
                            -18.0,
                            -19.0,
                            -20.0,
                            -21.0,
                            -22.0,
                            -23.0,
                            -24.0,
                            -25.0,
                            -26.0,
                            -27.0,
                            -28.0,
                            -29.0,
                            -30.0,
                            -31.0,
                            -32.0,
                        ],
                        0,
                    ],
                    "expected": [
                        -1.0,
                        -2.0,
                        -3.0,
                        -4.0,
                        -5.0,
                        -6.0,
                        -7.0,
                        -8.0,
                        -9.0,
                        -10.0,
                        -11.0,
                        -12.0,
                        -13.0,
                        -14.0,
                        -15.0,
                        -16.0,
                    ],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            -1.0,
                            -2.0,
                            -3.0,
                            -4.0,
                            -5.0,
                            -6.0,
                            -7.0,
                            -8.0,
                            -9.0,
                            -10.0,
                            -11.0,
                            -12.0,
                            -13.0,
                            -14.0,
                            -15.0,
                            -16.0,
                            -17.0,
                            -18.0,
                            -19.0,
                            -20.0,
                            -21.0,
                            -22.0,
                            -23.0,
                            -24.0,
                            -25.0,
                            -26.0,
                            -27.0,
                            -28.0,
                            -29.0,
                            -30.0,
                            -31.0,
                            -32.0,
                        ],
                        1,
                    ],
                    "expected": [
                        -17.0,
                        -18.0,
                        -19.0,
                        -20.0,
                        -21.0,
                        -22.0,
                        -23.0,
                        -24.0,
                        -25.0,
                        -26.0,
                        -27.0,
                        -28.0,
                        -29.0,
                        -30.0,
                        -31.0,
                        -32.0,
                    ],
                },
                # offset=0: fractional
                {
                    "inputs": [
                        [
                            0.1,
                            0.2,
                            0.3,
                            0.4,
                            0.5,
                            0.6,
                            0.7,
                            0.8,
                            0.9,
                            1.0,
                            1.1,
                            1.2,
                            1.3,
                            1.4,
                            1.5,
                            1.6,
                            1.7,
                            1.8,
                            1.9,
                            2.0,
                            2.1,
                            2.2,
                            2.3,
                            2.4,
                            2.5,
                            2.6,
                            2.7,
                            2.8,
                            2.9,
                            3.0,
                            3.1,
                            3.2,
                        ],
                        0,
                    ],
                    "expected": [
                        0.1,
                        0.2,
                        0.3,
                        0.4,
                        0.5,
                        0.6,
                        0.7,
                        0.8,
                        0.9,
                        1.0,
                        1.1,
                        1.2,
                        1.3,
                        1.4,
                        1.5,
                        1.6,
                    ],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            0.1,
                            0.2,
                            0.3,
                            0.4,
                            0.5,
                            0.6,
                            0.7,
                            0.8,
                            0.9,
                            1.0,
                            1.1,
                            1.2,
                            1.3,
                            1.4,
                            1.5,
                            1.6,
                            1.7,
                            1.8,
                            1.9,
                            2.0,
                            2.1,
                            2.2,
                            2.3,
                            2.4,
                            2.5,
                            2.6,
                            2.7,
                            2.8,
                            2.9,
                            3.0,
                            3.1,
                            3.2,
                        ],
                        1,
                    ],
                    "expected": [
                        1.7,
                        1.8,
                        1.9,
                        2.0,
                        2.1,
                        2.2,
                        2.3,
                        2.4,
                        2.5,
                        2.6,
                        2.7,
                        2.8,
                        2.9,
                        3.0,
                        3.1,
                        3.2,
                    ],
                },
                # offset=0: zeros and ones
                {
                    "inputs": [
                        [
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                        ],
                        0,
                    ],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                        ],
                        1,
                    ],
                    "expected": [
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                    ],
                },
            ],
        }
    )

    # vstore2 - store float2 to scalar array
    # For vstore, we need to verify the stored values
    # Input: vector to store, offset
    # Output: scalar array after store
    functions.append(
        {
            "name": "vstore2_float",
            "kernel_name": "test_vstore2_float",
            "input_type": "float2",  # vector input
            "output_type": "float",  # scalar array output
            "num_inputs": 2,  # vector + offset
            "tests": [
                # offset=0: store to [0,1]
                {"inputs": [[1.0, 2.0], 0], "expected": [1.0, 2.0, 0.0, 0.0]},
                # offset=1: store to [2,3]
                {"inputs": [[3.0, 4.0], 1], "expected": [0.0, 0.0, 3.0, 4.0]},
                # offset=0: negative values
                {"inputs": [[-1.0, -2.0], 0], "expected": [-1.0, -2.0, 0.0, 0.0]},
                # offset=1
                {"inputs": [[-3.0, -4.0], 1], "expected": [0.0, 0.0, -3.0, -4.0]},
                # offset=0: fractional
                {"inputs": [[0.5, 1.5], 0], "expected": [0.5, 1.5, 0.0, 0.0]},
                # offset=1
                {"inputs": [[2.5, 3.5], 1], "expected": [0.0, 0.0, 2.5, 3.5]},
                # offset=0: large values
                {"inputs": [[100.0, 200.0], 0], "expected": [100.0, 200.0, 0.0, 0.0]},
                # offset=1
                {"inputs": [[300.0, 400.0], 1], "expected": [0.0, 0.0, 300.0, 400.0]},
                # offset=0: zeros
                {"inputs": [[0.0, 0.0], 0], "expected": [0.0, 0.0, 0.0, 0.0]},
                # offset=1: ones
                {"inputs": [[1.0, 1.0], 1], "expected": [0.0, 0.0, 1.0, 1.0]},
            ],
        }
    )

    # vstore4 - store float4 to scalar array
    functions.append(
        {
            "name": "vstore4_float",
            "kernel_name": "test_vstore4_float",
            "input_type": "float4",
            "output_type": "float",
            "num_inputs": 2,  # vector + offset
            "tests": [
                # offset=0: store to [0,1,2,3]
                {
                    "inputs": [[1.0, 2.0, 3.0, 4.0], 0],
                    "expected": [1.0, 2.0, 3.0, 4.0, 0.0, 0.0, 0.0, 0.0],
                },
                # offset=1: store to [4,5,6,7]
                {
                    "inputs": [[5.0, 6.0, 7.0, 8.0], 1],
                    "expected": [0.0, 0.0, 0.0, 0.0, 5.0, 6.0, 7.0, 8.0],
                },
                # offset=0: negative values
                {
                    "inputs": [[-1.0, -2.0, -3.0, -4.0], 0],
                    "expected": [-1.0, -2.0, -3.0, -4.0, 0.0, 0.0, 0.0, 0.0],
                },
                # offset=1
                {
                    "inputs": [[-5.0, -6.0, -7.0, -8.0], 1],
                    "expected": [0.0, 0.0, 0.0, 0.0, -5.0, -6.0, -7.0, -8.0],
                },
                # offset=0: fractional
                {
                    "inputs": [[0.1, 0.2, 0.3, 0.4], 0],
                    "expected": [0.1, 0.2, 0.3, 0.4, 0.0, 0.0, 0.0, 0.0],
                },
                # offset=1
                {
                    "inputs": [[0.5, 0.6, 0.7, 0.8], 1],
                    "expected": [0.0, 0.0, 0.0, 0.0, 0.5, 0.6, 0.7, 0.8],
                },
                # offset=0: large values
                {
                    "inputs": [[100.0, 200.0, 300.0, 400.0], 0],
                    "expected": [100.0, 200.0, 300.0, 400.0, 0.0, 0.0, 0.0, 0.0],
                },
                # offset=1
                {
                    "inputs": [[500.0, 600.0, 700.0, 800.0], 1],
                    "expected": [0.0, 0.0, 0.0, 0.0, 500.0, 600.0, 700.0, 800.0],
                },
                # offset=0: zeros
                {
                    "inputs": [[0.0, 0.0, 0.0, 0.0], 0],
                    "expected": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                },
                # offset=1: ones
                {
                    "inputs": [[1.0, 1.0, 1.0, 1.0], 1],
                    "expected": [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0],
                },
            ],
        }
    )

    # vstore3 - store float3 to scalar array
    functions.append(
        {
            "name": "vstore3_float",
            "kernel_name": "test_vstore3_float",
            "input_type": "float3",
            "output_type": "float",
            "num_inputs": 2,  # vector + offset
            "tests": [
                # offset=0: store to [0,1,2]
                {"inputs": [[1.0, 2.0, 3.0], 0], "expected": [1.0, 2.0, 3.0, 0.0, 0.0, 0.0]},
                # offset=1: store to [3,4,5]
                {"inputs": [[4.0, 5.0, 6.0], 1], "expected": [0.0, 0.0, 0.0, 4.0, 5.0, 6.0]},
                # offset=0: negative values
                {"inputs": [[-1.0, -2.0, -3.0], 0], "expected": [-1.0, -2.0, -3.0, 0.0, 0.0, 0.0]},
                # offset=1
                {"inputs": [[-4.0, -5.0, -6.0], 1], "expected": [0.0, 0.0, 0.0, -4.0, -5.0, -6.0]},
                # offset=0: fractional
                {"inputs": [[0.1, 0.2, 0.3], 0], "expected": [0.1, 0.2, 0.3, 0.0, 0.0, 0.0]},
                # offset=1
                {"inputs": [[0.4, 0.5, 0.6], 1], "expected": [0.0, 0.0, 0.0, 0.4, 0.5, 0.6]},
                # offset=0: large values
                {
                    "inputs": [[100.0, 200.0, 300.0], 0],
                    "expected": [100.0, 200.0, 300.0, 0.0, 0.0, 0.0],
                },
                # offset=1
                {
                    "inputs": [[400.0, 500.0, 600.0], 1],
                    "expected": [0.0, 0.0, 0.0, 400.0, 500.0, 600.0],
                },
                # offset=0: zeros
                {"inputs": [[0.0, 0.0, 0.0], 0], "expected": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]},
                # offset=1: ones
                {"inputs": [[1.0, 1.0, 1.0], 1], "expected": [0.0, 0.0, 0.0, 1.0, 1.0, 1.0]},
            ],
        }
    )

    # vstore8 - store float8 to scalar array
    functions.append(
        {
            "name": "vstore8_float",
            "kernel_name": "test_vstore8_float",
            "input_type": "float8",
            "output_type": "float",
            "num_inputs": 2,  # vector + offset
            "tests": [
                # offset=0: store to [0-7]
                {
                    "inputs": [[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0], 0],
                    "expected": [
                        1.0,
                        2.0,
                        3.0,
                        4.0,
                        5.0,
                        6.0,
                        7.0,
                        8.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1: store to [8-15]
                {
                    "inputs": [[9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0], 1],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        9.0,
                        10.0,
                        11.0,
                        12.0,
                        13.0,
                        14.0,
                        15.0,
                        16.0,
                    ],
                },
                # offset=0: negative values
                {
                    "inputs": [[-1.0, -2.0, -3.0, -4.0, -5.0, -6.0, -7.0, -8.0], 0],
                    "expected": [
                        -1.0,
                        -2.0,
                        -3.0,
                        -4.0,
                        -5.0,
                        -6.0,
                        -7.0,
                        -8.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1
                {
                    "inputs": [[-9.0, -10.0, -11.0, -12.0, -13.0, -14.0, -15.0, -16.0], 1],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        -9.0,
                        -10.0,
                        -11.0,
                        -12.0,
                        -13.0,
                        -14.0,
                        -15.0,
                        -16.0,
                    ],
                },
                # offset=0: fractional
                {
                    "inputs": [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8], 0],
                    "expected": [
                        0.1,
                        0.2,
                        0.3,
                        0.4,
                        0.5,
                        0.6,
                        0.7,
                        0.8,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1
                {
                    "inputs": [[0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6], 1],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.9,
                        1.0,
                        1.1,
                        1.2,
                        1.3,
                        1.4,
                        1.5,
                        1.6,
                    ],
                },
                # offset=0: large values
                {
                    "inputs": [[100.0, 200.0, 300.0, 400.0, 500.0, 600.0, 700.0, 800.0], 0],
                    "expected": [
                        100.0,
                        200.0,
                        300.0,
                        400.0,
                        500.0,
                        600.0,
                        700.0,
                        800.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1
                {
                    "inputs": [[900.0, 1000.0, 1100.0, 1200.0, 1300.0, 1400.0, 1500.0, 1600.0], 1],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        900.0,
                        1000.0,
                        1100.0,
                        1200.0,
                        1300.0,
                        1400.0,
                        1500.0,
                        1600.0,
                    ],
                },
                # offset=0: zeros
                {
                    "inputs": [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1: ones
                {
                    "inputs": [[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 1],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                    ],
                },
            ],
        }
    )

    # vstore16 - store float16 to scalar array
    functions.append(
        {
            "name": "vstore16_float",
            "kernel_name": "test_vstore16_float",
            "input_type": "float16",
            "output_type": "float",
            "num_inputs": 2,  # vector + offset
            "tests": [
                # offset=0: store to [0-15]
                {
                    "inputs": [
                        [
                            1.0,
                            2.0,
                            3.0,
                            4.0,
                            5.0,
                            6.0,
                            7.0,
                            8.0,
                            9.0,
                            10.0,
                            11.0,
                            12.0,
                            13.0,
                            14.0,
                            15.0,
                            16.0,
                        ],
                        0,
                    ],
                    "expected": [
                        1.0,
                        2.0,
                        3.0,
                        4.0,
                        5.0,
                        6.0,
                        7.0,
                        8.0,
                        9.0,
                        10.0,
                        11.0,
                        12.0,
                        13.0,
                        14.0,
                        15.0,
                        16.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1: store to [16-31]
                {
                    "inputs": [
                        [
                            17.0,
                            18.0,
                            19.0,
                            20.0,
                            21.0,
                            22.0,
                            23.0,
                            24.0,
                            25.0,
                            26.0,
                            27.0,
                            28.0,
                            29.0,
                            30.0,
                            31.0,
                            32.0,
                        ],
                        1,
                    ],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        17.0,
                        18.0,
                        19.0,
                        20.0,
                        21.0,
                        22.0,
                        23.0,
                        24.0,
                        25.0,
                        26.0,
                        27.0,
                        28.0,
                        29.0,
                        30.0,
                        31.0,
                        32.0,
                    ],
                },
                # offset=0: negative values
                {
                    "inputs": [
                        [
                            -1.0,
                            -2.0,
                            -3.0,
                            -4.0,
                            -5.0,
                            -6.0,
                            -7.0,
                            -8.0,
                            -9.0,
                            -10.0,
                            -11.0,
                            -12.0,
                            -13.0,
                            -14.0,
                            -15.0,
                            -16.0,
                        ],
                        0,
                    ],
                    "expected": [
                        -1.0,
                        -2.0,
                        -3.0,
                        -4.0,
                        -5.0,
                        -6.0,
                        -7.0,
                        -8.0,
                        -9.0,
                        -10.0,
                        -11.0,
                        -12.0,
                        -13.0,
                        -14.0,
                        -15.0,
                        -16.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            -17.0,
                            -18.0,
                            -19.0,
                            -20.0,
                            -21.0,
                            -22.0,
                            -23.0,
                            -24.0,
                            -25.0,
                            -26.0,
                            -27.0,
                            -28.0,
                            -29.0,
                            -30.0,
                            -31.0,
                            -32.0,
                        ],
                        1,
                    ],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        -17.0,
                        -18.0,
                        -19.0,
                        -20.0,
                        -21.0,
                        -22.0,
                        -23.0,
                        -24.0,
                        -25.0,
                        -26.0,
                        -27.0,
                        -28.0,
                        -29.0,
                        -30.0,
                        -31.0,
                        -32.0,
                    ],
                },
                # offset=0: fractional
                {
                    "inputs": [
                        [
                            0.1,
                            0.2,
                            0.3,
                            0.4,
                            0.5,
                            0.6,
                            0.7,
                            0.8,
                            0.9,
                            1.0,
                            1.1,
                            1.2,
                            1.3,
                            1.4,
                            1.5,
                            1.6,
                        ],
                        0,
                    ],
                    "expected": [
                        0.1,
                        0.2,
                        0.3,
                        0.4,
                        0.5,
                        0.6,
                        0.7,
                        0.8,
                        0.9,
                        1.0,
                        1.1,
                        1.2,
                        1.3,
                        1.4,
                        1.5,
                        1.6,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            1.7,
                            1.8,
                            1.9,
                            2.0,
                            2.1,
                            2.2,
                            2.3,
                            2.4,
                            2.5,
                            2.6,
                            2.7,
                            2.8,
                            2.9,
                            3.0,
                            3.1,
                            3.2,
                        ],
                        1,
                    ],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        1.7,
                        1.8,
                        1.9,
                        2.0,
                        2.1,
                        2.2,
                        2.3,
                        2.4,
                        2.5,
                        2.6,
                        2.7,
                        2.8,
                        2.9,
                        3.0,
                        3.1,
                        3.2,
                    ],
                },
                # offset=0: large values
                {
                    "inputs": [
                        [
                            100.0,
                            200.0,
                            300.0,
                            400.0,
                            500.0,
                            600.0,
                            700.0,
                            800.0,
                            900.0,
                            1000.0,
                            1100.0,
                            1200.0,
                            1300.0,
                            1400.0,
                            1500.0,
                            1600.0,
                        ],
                        0,
                    ],
                    "expected": [
                        100.0,
                        200.0,
                        300.0,
                        400.0,
                        500.0,
                        600.0,
                        700.0,
                        800.0,
                        900.0,
                        1000.0,
                        1100.0,
                        1200.0,
                        1300.0,
                        1400.0,
                        1500.0,
                        1600.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1
                {
                    "inputs": [
                        [
                            1700.0,
                            1800.0,
                            1900.0,
                            2000.0,
                            2100.0,
                            2200.0,
                            2300.0,
                            2400.0,
                            2500.0,
                            2600.0,
                            2700.0,
                            2800.0,
                            2900.0,
                            3000.0,
                            3100.0,
                            3200.0,
                        ],
                        1,
                    ],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        1700.0,
                        1800.0,
                        1900.0,
                        2000.0,
                        2100.0,
                        2200.0,
                        2300.0,
                        2400.0,
                        2500.0,
                        2600.0,
                        2700.0,
                        2800.0,
                        2900.0,
                        3000.0,
                        3100.0,
                        3200.0,
                    ],
                },
                # offset=0: zeros
                {
                    "inputs": [
                        [
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                            0.0,
                        ],
                        0,
                    ],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                    ],
                },
                # offset=1: ones
                {
                    "inputs": [
                        [
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                            1.0,
                        ],
                        1,
                    ],
                    "expected": [
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        0.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                        1.0,
                    ],
                },
            ],
        }
    )

    # Create JSON structure
    data = {
        "category": "vector_load_store_functions",
        "kernel_file": "kernels/vector_load_store_kernel.cl",
        "functions": functions,
    }

    # Write to file
    with open("test_data/vector_load_store_functions.json", "w") as f:
        json.dump(data, f, indent=2)

    print(f"Created vector_load_store_functions.json with {len(functions)} functions")
    print("Total test cases:", sum(len(f["tests"]) for f in functions))


if __name__ == "__main__":
    create_vload_vstore_test_data()
    print("Vector load/store functions test data generation complete!")
